version: "2"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
volumes:
  esdata01:
    driver: local

